language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "1.0"
  - "1.6"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
before_install:
  - npm install -g npm
before_script:
  - npm install
script: 'mocha test.js'
notifications:
  email: false
